spring.application.name=servicehub-api

# Configuração do PostgreSQL (Ajuste a senha do seu Postgres se necessário)
spring.datasource.url=jdbc:postgresql://localhost:5432/servicehub_db
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Swagger UI
springdoc.swagger-ui.path=/swagger-ui.html
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect